service: service-name-test
provider: 
  name: aws
  region: us-east-2
  runtime: python3.8
  stage: "${opt:stage, \"dev\"}"

plugins:
  - serverless-package-external

functions: 
  app: 
    environment: 
      STAGE: "${self:provider.stage}"
    events: 
      - 
        http: 
          method: any
          path: "/{proxy+}"
    handler: main.handler
    package: 
      exclude: 
        - requirements.txt
        - package.json
        - package-lock.json
        - .serverless/**
        - .virtualenv/**
        - .venv/**
        - node_modules/**
        - __pycache__/**
      include: 
        - main.py
package: 
  individually: true

custom:
  packageExternal:
    external:
      - '../libs/lib_one/lib_one'      